version: "3.9"
services:
  lb:
    image: nginx:alpine
    ports:
      - "5003:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  brs_1:
    image: "brs-wshop:latest"
    deploy:
      mode: replicated
      replicas: 3
  
